package dev.benfan.models;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Bands")
public class BandInfo {
    public BandInfo(){
    }
    @DynamoDBHashKey(attributeName = "bandID")
    @DynamoDBAutoGeneratedKey
    public String bandID;
    @DynamoDBAttribute(attributeName = "BandName")
    public String bandName;
    @DynamoDBAttribute(attributeName = "Genre")
    public String genre;

    public String getBandID() {
        return bandID;
    }

    public void setBandID(String bandID) {
        this.bandID = bandID;
    }

    public String getBandName() {
        return bandName;
    }

    public void setBandName(String bandName) {
        this.bandName = bandName;
    }

    public String getGenre() {
        return genre;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }
}
